/**
 * lib/fit.ts must say exactly what the prototype says (reference/room-planner.html).
 * The fixture is generated by `node scripts/prototype-fit-fixture.mjs` from the prototype's own code.
 *   npm test
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { ROOMS } from "../content/rooms";
import { MODELS, SIDES, bestSpot, evaluate, fitSummary, goodSpots, nextWall, nudge, positionsFor, wallValid } from "../lib/fit";

type Row = { u: number; ok: boolean; wallOK: boolean; heightOK: boolean; zoneOK: boolean; wallBy: string | null; zoneBy: string | null; top: number };
type Fixture = Record<string, Record<"std" | "xt", { goodSpots: number; walls: Record<string, Row[]> }>>;
const fixture: Fixture = JSON.parse(readFileSync(new URL("./fixtures/prototype-fit.json", import.meta.url), "utf8"));

describe("studs", () => {
  for (const room of ROOMS)
    for (const side of SIDES)
      it(`${room.key} ${side} wall has the prototype's studs`, () => {
        assert.deepEqual(positionsFor(room, side), fixture[room.key].std.walls[side].map((r) => r.u));
      });
  it("bedroom back wall: 8 studs, 16 in apart, from -56 to 56", () => {
    const b = ROOMS[0];
    assert.deepEqual(positionsFor(b, "back"), [-56, -40, -24, -8, 8, 24, 40, 56]);
  });
});

describe("evaluate", () => {
  for (const room of ROOMS)
    for (const mk of ["std", "xt"] as const)
      for (const side of SIDES)
        it(`${room.key} / ${mk} / ${side}: every stud matches the prototype`, () => {
          for (const row of fixture[room.key][mk].walls[side]) {
            const e = evaluate(room, MODELS[mk], side, row.u);
            assert.deepEqual({ u: row.u, ok: e.ok, wallOK: e.wallOK, heightOK: e.heightOK, zoneOK: e.zoneOK, wallBy: e.wallBy ?? null, zoneBy: e.zoneBy ?? null, top: e.top }, row, `${room.key} ${mk} ${side} u=${row.u}`);
          }
        });
  it("names the blocker and the zone obstacle", () => {
    const b = ROOMS[0];
    const e = evaluate(b, MODELS.std, "back", 8);
    assert.equal(e.wallOK, false);
    assert.equal(e.wallBy, "the bed and nightstands");
    assert.equal(e.zoneBy, "the bed");
  });
  it("XT clears the 8 ft bedroom ceiling minus 2 in? No: 102 > 94", () => {
    const e = evaluate(ROOMS[0], MODELS.xt, "left", -18);
    assert.equal(e.heightOK, false);
    assert.equal(e.top, 102);
  });
  it("patio is open sky: the fence height itself is the limit", () => {
    const patio = ROOMS.find((r) => r.key === "patio")!;
    assert.equal(evaluate(patio, MODELS.std, "left", -56).heightOK, true); // 77 <= 84
    assert.equal(evaluate(patio, MODELS.xt, "left", -56).heightOK, false); // 102 > 84
    assert.equal(evaluate(patio, MODELS.xt, "back", -32).heightOK, true); // 102 <= 120 house wall
  });
});

describe("goodSpots", () => {
  for (const room of ROOMS)
    for (const mk of ["std", "xt"] as const)
      it(`${room.key} / ${mk} = ${fixture[room.key][mk].goodSpots}`, () => {
        assert.equal(goodSpots(room, MODELS[mk]), fixture[room.key][mk].goodSpots);
      });
  it("fitSummary lists every room with both counts", () => {
    const s = fitSummary();
    assert.equal(s.length, ROOMS.length);
    for (const r of ROOMS) {
      const row = s.find((x) => x.room === r.name)!;
      assert.equal(row.std, fixture[r.key].std.goodSpots);
      assert.equal(row.xt, fixture[r.key].xt.goodSpots);
    }
  });
});

describe("navigation", () => {
  it("nudge steps one stud along the wall and respects the wall's direction", () => {
    const b = ROOMS[0];
    const valid = wallValid(b, "left");
    assert.ok(valid.includes(-18));
    assert.equal(nudge(b, "left", -18, 1), valid.slice().reverse().find((u) => u < -18) ?? null); // +1 on the left wall moves toward the viewer's right = smaller u
    assert.equal(nudge(b, "back", -56, -1), null);
  });
  it("bestSpot prefers a fitting stud nearest the middle", () => {
    const b = ROOMS[0];
    const u = bestSpot(b, MODELS.std, "left")!;
    assert.ok(evaluate(b, MODELS.std, "left", u).ok);
  });
  it("nextWall cycles left -> back -> right and lands on a valid stud", () => {
    const g = ROOMS.find((r) => r.key === "garage")!;
    const n = nextWall(g, MODELS.std, "left")!;
    assert.equal(n.side, "back");
    assert.ok(wallValid(g, n.side).includes(n.u));
    assert.equal(nextWall(g, MODELS.std, "right")!.side, "left");
  });
  it("nextWall wraps to the same wall when it is the only one with a valid stud (bedroom)", () => {
    const b = ROOMS[0];
    assert.deepEqual(wallValid(b, "back"), []);
    assert.deepEqual(wallValid(b, "right"), []);
    const n = nextWall(b, MODELS.std, "left")!;
    assert.equal(n.side, "left");
    assert.ok(evaluate(b, MODELS.std, "left", n.u).ok);
  });
});
