/**
 * EXAMPLE exercise library for the plan builder.
 *
 * Every row here is a placeholder written in wellness language and marked approved: false.
 * The plan builder shows the "Example plan · placeholder exercises" badge whenever any
 * unapproved row is used. This file will be replaced by Dr. Santiago's approved library;
 * keep the field names, they are what the builder and the future server route read.
 *
 * anchorRow: anchor row counted from the floor, 1..48 (16 per section, three sections).
 */
export type Region = "shoulders" | "arms" | "core" | "hips" | "knees" | "ankles" | "whole";
export type Goal = "strength" | "mobility" | "balance";
export type Level = "gentle" | "standard";
export type Position = "standing" | "seated" | "kneeling";

export interface Exercise {
  id: string;
  name: string;
  region: Region;
  goal: Goal[];
  level: Level;
  position: Position;
  anchorRow: number;
  anchorLandmark: string;
  band: "none" | 'mini loop 10"' | 'loop 22"';
  rail: boolean;
  setup: string;
  steps: string[];
  reps: string;
  cue: string;
  why: string;
  easier: string;
  harder: string;
  stop: string;
  media: string | null;
  approved: boolean;
}

export const REGIONS: { id: Region; label: string; short: string }[] = [
  { id: "shoulders", label: "Shoulders", short: "Shoulders" },
  { id: "arms", label: "Arms & grip", short: "Arms" },
  { id: "core", label: "Core & back", short: "Core" },
  { id: "hips", label: "Hips", short: "Hips" },
  { id: "knees", label: "Knees", short: "Knees" },
  { id: "ankles", label: "Ankles & feet", short: "Ankles" },
  { id: "whole", label: "Whole body · Balance", short: "Whole body" },
];

export const GOALS: { id: Goal; label: string; line: string }[] = [
  { id: "strength", label: "Strength", line: "Push and pull against a band" },
  { id: "mobility", label: "Mobility", line: "Reach, bend and move more freely" },
  { id: "balance", label: "Balance", line: "Practice standing steady" },
];

export const exercises: Exercise[] = [
  {
    id: "shoulder-pull-apart",
    name: "Band pull-apart",
    region: "shoulders",
    goal: ["strength"],
    level: "standard",
    position: "standing",
    anchorRow: 30,
    anchorLandmark: "shoulder height",
    band: 'loop 22"',
    rail: false,
    setup: "Clip the loop at shoulder height. Hold one end in each hand, arms straight in front.",
    steps: ["Stand tall, an arm's length from the board.", "Pull the band apart until your hands are level with your shoulders.", "Pause, then return slowly."],
    reps: "2 sets of 10",
    cue: "Keep your shoulders down and away from your ears.",
    why: "Works the muscles between the shoulder blades that support posture and reaching.",
    easier: "Use the mini loop, or bend your elbows slightly.",
    harder: "Hold the open position for a count of three.",
    stop: "Stop if you feel sharp pain in the shoulder or neck.",
    media: null,
    approved: false,
  },
  {
    id: "shoulder-wall-slide",
    name: "Wall reach and slide",
    region: "shoulders",
    goal: ["mobility"],
    level: "gentle",
    position: "standing",
    anchorRow: 36,
    anchorLandmark: "a hand's width above shoulder height",
    band: "none",
    rail: true,
    setup: "Stand facing the board. Rest your fingertips on an anchor point at shoulder height.",
    steps: ["Slide your fingertips up the board as far as feels comfortable.", "Hold for a breath.", "Slide back down."],
    reps: "8 reaches each arm",
    cue: "Let your ribs stay down as your arm goes up.",
    why: "Practises overhead reach with the board as a guide.",
    easier: "Stop the slide a little lower.",
    harder: "Lift your fingertips off the board at the top for a count of two.",
    stop: "Stop if the shoulder pinches at the top.",
    media: null,
    approved: false,
  },
  {
    id: "arm-row",
    name: "Standing row",
    region: "arms",
    goal: ["strength"],
    level: "standard",
    position: "standing",
    anchorRow: 22,
    anchorLandmark: "elbow height",
    band: 'loop 22"',
    rail: false,
    setup: "Clip the loop at elbow height. Hold the band with both hands and step back until it is snug.",
    steps: ["Pull your elbows straight back past your sides.", "Squeeze between the shoulder blades.", "Return slowly."],
    reps: "2 sets of 10",
    cue: "Elbows brush your ribs.",
    why: "Strengthens the pulling muscles used for opening doors and lifting bags.",
    easier: "Step closer to the board.",
    harder: "Pull with one arm at a time.",
    stop: "Stop if you feel pain in the elbow or wrist.",
    media: null,
    approved: false,
  },
  {
    id: "arm-overhead-hold",
    name: "Overhead reach hold",
    region: "arms",
    goal: ["mobility", "strength"],
    level: "gentle",
    position: "standing",
    anchorRow: 40,
    anchorLandmark: "just above head height",
    band: "none",
    rail: true,
    setup: "Stand facing the board, one hand on the rail.",
    steps: ["Reach up with the free hand and hold an anchor point above your head.", "Hold for five slow breaths.", "Switch hands."],
    reps: "3 holds each side",
    cue: "Grow tall through the top of your head.",
    why: "Keeps overhead reach comfortable for cupboards and shelves.",
    easier: "Choose an anchor point at eye level.",
    harder: "Let go of the rail while you hold.",
    stop: "Stop if your fingers tingle or go numb.",
    media: null,
    approved: false,
  },
  {
    id: "core-press-out",
    name: "Anti-rotation press",
    region: "core",
    goal: ["strength"],
    level: "standard",
    position: "standing",
    anchorRow: 26,
    anchorLandmark: "chest height",
    band: 'loop 22"',
    rail: false,
    setup: "Clip the loop at chest height. Stand side-on to the board and hold the band at your chest with both hands.",
    steps: ["Press your hands straight out in front of you.", "Hold for a count of three without letting your body turn.", "Bring your hands back to your chest."],
    reps: "8 each side",
    cue: "Stay square to the wall in front of you.",
    why: "Trains the trunk to stay steady while your arms move.",
    easier: "Step closer to the board.",
    harder: "Step further away.",
    stop: "Stop if your back aches.",
    media: null,
    approved: false,
  },
  {
    id: "core-hinge",
    name: "Hip hinge with the rail",
    region: "core",
    goal: ["mobility"],
    level: "gentle",
    position: "standing",
    anchorRow: 20,
    anchorLandmark: "hip height",
    band: "none",
    rail: true,
    setup: "Stand facing the board with both hands on the rails at hip height.",
    steps: ["Send your hips back as if closing a drawer with them.", "Let your chest tip forward with a long back.", "Push through your feet to stand tall."],
    reps: "10 slow hinges",
    cue: "Knees soft, back long.",
    why: "Practises the bending pattern used for picking things up.",
    easier: "Hinge a little less.",
    harder: "Hold the bottom for a count of three.",
    stop: "Stop if you feel pain in the lower back.",
    media: null,
    approved: false,
  },
  {
    id: "hip-side-step",
    name: "Side step with the rail",
    region: "hips",
    goal: ["strength", "balance"],
    level: "standard",
    position: "standing",
    anchorRow: 20,
    anchorLandmark: "hip height",
    band: 'mini loop 10"',
    rail: true,
    setup: "Place the mini loop just above your knees. Stand facing the board, one hand on the rail.",
    steps: ["Step sideways against the band.", "Bring the other foot to follow.", "Take four steps one way, then four back."],
    reps: "3 rounds",
    cue: "Keep your toes pointing at the board.",
    why: "Strengthens the outside of the hips, which help you stay steady on one leg.",
    easier: "Take smaller steps, or skip the band.",
    harder: "Lower the loop to your shins.",
    stop: "Stop if the hip clicks with pain.",
    media: null,
    approved: false,
  },
  {
    id: "hip-opener",
    name: "Standing hip opener",
    region: "hips",
    goal: ["mobility"],
    level: "gentle",
    position: "standing",
    anchorRow: 24,
    anchorLandmark: "chest height",
    band: "none",
    rail: true,
    setup: "Stand facing the board, both hands on the rails.",
    steps: ["Lift one knee to a comfortable height.", "Open the knee out to the side, then bring it back.", "Lower the foot with control."],
    reps: "6 each side",
    cue: "Move the leg, not the body.",
    why: "Keeps the hips moving freely for stairs and getting in and out of the car.",
    easier: "Lift the knee lower.",
    harder: "Use one hand on the rail.",
    stop: "Stop if the groin pinches.",
    media: null,
    approved: false,
  },
  {
    id: "knee-sit-to-stand",
    name: "Rail-assisted mini squat",
    region: "knees",
    goal: ["strength"],
    level: "standard",
    position: "standing",
    anchorRow: 24,
    anchorLandmark: "chest height",
    band: "none",
    rail: true,
    setup: "Stand facing the board with both hands on the rails at chest height, feet hip-width apart.",
    steps: ["Bend your knees and sit back a little, as if toward a chair.", "Go only as low as feels comfortable.", "Push through your heels to stand."],
    reps: "2 sets of 8",
    cue: "Knees follow your toes.",
    why: "Builds the leg strength used every time you stand up from a chair.",
    easier: "Bend the knees less.",
    harder: "Slow the way down to a count of three.",
    stop: "Stop if the knee pain rises above mild.",
    media: null,
    approved: false,
  },
  {
    id: "knee-march",
    name: "Supported march",
    region: "knees",
    goal: ["mobility", "balance"],
    level: "gentle",
    position: "standing",
    anchorRow: 24,
    anchorLandmark: "chest height",
    band: "none",
    rail: true,
    setup: "Stand facing the board, one hand on the rail.",
    steps: ["Lift one knee, pause, and lower.", "Switch sides.", "Keep a slow, even rhythm."],
    reps: "20 marches",
    cue: "Tall through the spine.",
    why: "Practises bending the knee and standing on one leg with support.",
    easier: "Use both hands on the rails.",
    harder: "Hover the hand above the rail.",
    stop: "Stop if you feel unsteady in a way the rail does not fix.",
    media: null,
    approved: false,
  },
  {
    id: "ankle-heel-raise",
    name: "Heel raise with the rail",
    region: "ankles",
    goal: ["strength"],
    level: "standard",
    position: "standing",
    anchorRow: 24,
    anchorLandmark: "chest height",
    band: "none",
    rail: true,
    setup: "Stand facing the board, both hands resting on the rails.",
    steps: ["Rise onto the balls of your feet.", "Pause at the top.", "Lower slowly."],
    reps: "2 sets of 12",
    cue: "Press evenly through the big toe and little toe.",
    why: "Strengthens the calves and the push-off used in walking.",
    easier: "Rise a little less.",
    harder: "Try one foot at a time.",
    stop: "Stop if you feel cramping that does not ease.",
    media: null,
    approved: false,
  },
  {
    id: "ankle-rock",
    name: "Ankle rock",
    region: "ankles",
    goal: ["mobility"],
    level: "gentle",
    position: "standing",
    anchorRow: 24,
    anchorLandmark: "chest height",
    band: "none",
    rail: true,
    setup: "Stand facing the board with both hands on the rails, feet hip-width apart.",
    steps: ["Rock forward onto your toes.", "Rock back onto your heels.", "Keep the movement slow and small."],
    reps: "15 rocks",
    cue: "Let the rails take the weight you need them to.",
    why: "Keeps the ankles moving through the range used on slopes and stairs.",
    easier: "Rock a smaller distance.",
    harder: "Lighten your grip on the rails.",
    stop: "Stop if the ankle pinches at either end.",
    media: null,
    approved: false,
  },
  {
    id: "balance-single-leg",
    name: "Single-leg stand with the rail",
    region: "whole",
    goal: ["balance"],
    level: "standard",
    position: "standing",
    anchorRow: 24,
    anchorLandmark: "chest height",
    band: "none",
    rail: true,
    setup: "Stand facing the board with one hand on the rail.",
    steps: ["Lift one foot a little off the floor.", "Hold for up to ten seconds.", "Switch sides."],
    reps: "3 holds each side",
    cue: "Eyes on one anchor point in front of you.",
    why: "Practises standing on one leg, which every step asks of you.",
    easier: "Keep both hands on the rails, or just the toes of the lifted foot on the floor.",
    harder: "Hover the hand above the rail.",
    stop: "Stop if you feel dizzy.",
    media: null,
    approved: false,
  },
  {
    id: "balance-tandem",
    name: "Tandem stance",
    region: "whole",
    goal: ["balance"],
    level: "gentle",
    position: "standing",
    anchorRow: 24,
    anchorLandmark: "chest height",
    band: "none",
    rail: true,
    setup: "Stand side-on to the board with the near hand on the rail.",
    steps: ["Place one foot directly in front of the other, heel to toe.", "Hold for up to ten seconds.", "Switch feet."],
    reps: "3 holds each way",
    cue: "Soft knees, quiet breath.",
    why: "Narrows your base of support in a safe, supported way.",
    easier: "Leave a small gap between the feet.",
    harder: "Turn your head slowly side to side while you hold.",
    stop: "Stop if you need to grab the rail to keep from stepping out.",
    media: null,
    approved: false,
  },
  {
    id: "balance-weight-shift",
    name: "Side-to-side weight shift",
    region: "whole",
    goal: ["balance", "mobility"],
    level: "gentle",
    position: "standing",
    anchorRow: 24,
    anchorLandmark: "chest height",
    band: "none",
    rail: true,
    setup: "Stand facing the board with both hands on the rails, feet wider than your hips.",
    steps: ["Shift your weight onto one foot.", "Pause, then shift to the other.", "Keep the movement slow."],
    reps: "10 shifts each way",
    cue: "Let the hips lead, shoulders follow.",
    why: "A calm way to practise moving your weight over each leg.",
    easier: "Shift a smaller distance.",
    harder: "Lift the unweighted heel at the end of each shift.",
    stop: "Stop if you feel light-headed.",
    media: null,
    approved: false,
  },
];
