// GENERATED by scripts/optimize-images.mjs. Do not edit by hand.
export const generatedImages = {
  "6l5a6431": {
    "name": "6l5a6431",
    "file": "6L5A6431.webp",
    "width": 600,
    "height": 900,
    "widths": [
      360,
      480,
      600
    ],
    "blur": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZACdIExCN1LFabD9V4XwJgAA/tvCJ3OL/vVRXVaKxqdVSoh1Djp4JM13/Xct7wnS8iyP+l3DB1dJNmk8mF4JsoIxTj0RCVugcOh42XwuVGYk+sTSqIvadlo6H96vWJsM7xToAAA="
  },
  "img-6091": {
    "name": "img-6091",
    "file": "IMG_6091.webp",
    "width": 600,
    "height": 1067,
    "widths": [
      360,
      480,
      600
    ],
    "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACQBACdASoQABwAPu1iqk4ppaQiMAgBMB2JYwC7AYx4tWde/6eZNam4CmsmAAAA/tZo8fZUC0ouJpEIuWuGloyyabwuj5FTGQwcBxALSwDFoEi7ye/PluOd4ueBRlcJZhHZXSosl4Ha+lffEN6nRgexvjvh+MDh0aPAAA=="
  },
  "img-7059": {
    "name": "img-7059",
    "file": "IMG_7059.webp",
    "width": 500,
    "height": 649,
    "widths": [
      360,
      480,
      500
    ],
    "blur": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBACdASoQABUAPu1kqU4ppaOiMAgBMB2JaAC7ABuMaLzS40nnmKKMQAD3B5X5tmHymm1IGGfAfq62bI2SukjU1vbpo762CbfdAjaiSgL2B5Um9PS1gd5b+MI0FQUGo0Pf3al2M2pLRidplwwZIDjbnClv85QabfuWBXr9yuo+AAAA"
  },
  "img-e4807": {
    "name": "img-e4807",
    "file": "IMG_E4807.webp",
    "width": 600,
    "height": 1066,
    "widths": [
      360,
      480,
      600
    ],
    "blur": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAQBACdASoQABwAPu1iqU2ppaQiMAgBMB2JYgCdAGjr6LDqUXJOKM558AD+7liSMnzJPtmC2ahc2bQVOX7I3S5p6zmdph8fB/050y5wo/0djOISEt/i7M5t4vv6e+0h3dr3rnTQkuIns7mkI0Pmlkfv9wHvzH30xrKoRInkKCP54vWg44R136m4CcdcDcVa4MqU9YvNUBalr9XgAAA="
  },
  "varysystems-gym-r1": {
    "name": "varysystems-gym-r1",
    "file": "VarySystems_gym_r1.webp",
    "width": 900,
    "height": 500,
    "widths": [
      360,
      480,
      640,
      768,
      900
    ],
    "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoQAAkAA4BaJZACw8iAAQhwRsR0AOEkL/0dILbUzeFcdGS6naxr1q0JPKxNy+GzTM747Pw3led4C8S12R5jSjAA"
  },
  "varysystems-modernroom-r1-1": {
    "name": "varysystems-modernroom-r1-1",
    "file": "VarySystems_modernroom_r1_1.webp",
    "width": 900,
    "height": 709,
    "widths": [
      360,
      480,
      640,
      768,
      900
    ],
    "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAA0AA4BaJZQC06ED5AZHNxAAAPrpI412r0MgfJH+HXeJxd/OCgVyV7LsoH5TPOhfZulJK/WoYttlm2PTRM1bMzPVmTKq56V4b0oA"
  },
  "mantoleft": {
    "name": "mantoleft",
    "file": "mantoleft.webp",
    "width": 600,
    "height": 656,
    "widths": [
      360,
      480,
      600
    ],
    "blur": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABQBACdASoQABEAPu1iqU2ppaOiMAgBMB2JYwC1CMo/+AvBcN1zMTWiA26AAP7HKzHJJvfdyPe7ZpIlN3mSkV26/aQhZXYsu82bcTw5QX3cYcg6Eb5cQGTeOXnVGVaIINVy19A8Us89lw5urCHqxRXoq5QlOko8ncF0CUBdwAA="
  },
  "outside-pool": {
    "name": "outside-pool",
    "file": "outside-pool.webp",
    "width": 600,
    "height": 800,
    "widths": [
      360,
      480,
      600
    ],
    "blur": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAADQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JagCdMoFWVnYANqeTr2R2CqXLOcWnAAD+42Mu3kWZvLG8BhKm5HvpoXSKTVdb5MuIwcKnra4f25ZDFRxSxSToN7ytAOFlU4kE/46MKdSB+jDU4MwjRBXjFTK7YAPaM9tisuLMW+dpzShuDipIShdZ+ZWdPeQlV3LvvYQvDg5SS72Xki4Rlm4XWc13/1j+Z/PhSgzQwAA="
  }
} as const;
export type GeneratedImageName = keyof typeof generatedImages;
