/**
 * Reads public/images/originals/*, writes AVIF + WebP at responsive widths to
 * public/images/opt/<name>/<width>.<ext>, and generates content/images.generated.ts
 * with intrinsic sizes and a tiny blur placeholder for every image (no layout shift).
 *
 *   node scripts/optimize-images.mjs
 *
 * next/image also optimizes on demand on Vercel; the pre-generated set is what the
 * <Picture> component uses for plain <picture> tags (parallax layers, OG image).
 */
import sharp from "sharp";
import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const SRC = path.resolve("public/images/originals");
const OUT = path.resolve("public/images/opt");
const WIDTHS = [360, 480, 640, 768, 1024, 1280, 1536, 1920];

const files = (await readdir(SRC)).filter((f) => /\.(jpe?g|png|webp|avif)$/i.test(f));
const entries = [];
for (const f of files) {
  const name = f.replace(/\.[^.]+$/, "").toLowerCase().replace(/[^a-z0-9-]+/g, "-");
  const img = sharp(path.join(SRC, f));
  const meta = await img.metadata();
  const dir = path.join(OUT, name);
  await mkdir(dir, { recursive: true });
  const widths = WIDTHS.filter((w) => w <= meta.width);
  if (!widths.includes(meta.width)) widths.push(meta.width);
  for (const w of widths) {
    await img.clone().resize({ width: w, withoutEnlargement: true }).avif({ quality: 55 }).toFile(path.join(dir, `${w}.avif`));
    await img.clone().resize({ width: w, withoutEnlargement: true }).webp({ quality: 78 }).toFile(path.join(dir, `${w}.webp`));
  }
  const blur = await img.clone().resize({ width: 16 }).webp({ quality: 40 }).toBuffer();
  entries.push({ name, file: f, width: meta.width, height: meta.height, widths, blur: `data:image/webp;base64,${blur.toString("base64")}` });
  console.log("optimized", f, `${meta.width}x${meta.height}`, `-> ${widths.length} widths`);
}

const ts = `// GENERATED by scripts/optimize-images.mjs. Do not edit by hand.
export const generatedImages = ${JSON.stringify(Object.fromEntries(entries.map((e) => [e.name, e])), null, 2)} as const;
export type GeneratedImageName = keyof typeof generatedImages;
`;
await writeFile(path.resolve("content/images.generated.ts"), ts);
console.log("wrote content/images.generated.ts");
